version: '3'
networks:
  laravel:
    driver: bridge
services:
  site:
    image: nginx:stable-alpine
    container_name: site
    ports:
      - "8080:80"
    volumes:
      - .:/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel
  app:
    build:
      context: docker/php
    container_name: app
    volumes:
      - .:/www
      - ./docker/php/supervisor:/etc/supervisor/custom.d/
      - ./docker/php/config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    depends_on:
      - ngrok
    networks:
      - laravel
  pgsql:
    build:
      context: docker/postgres
    container_name: pgsql
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./docker/datas/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    platform: linux/amd64
    command: http site:80
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    networks:
      - laravel
